-- AlterTable
ALTER TABLE "Alert" ADD COLUMN     "appointmentsCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "centerLatitude" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "centerLongitude" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "commonSymptoms" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "description" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "outbreakRadiusKm" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "possibleDiseases" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "precautions" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "severity" TEXT NOT NULL DEFAULT 'Unknown',
ADD COLUMN     "symptomCounts" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "symptomFrequencies" DOUBLE PRECISION[] DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN     "thresholdUsed" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
